#
#  ________       _____        ___           ___       __ 
# /_  __/ /  ___ / ___/__  ___/ (_)__  ___ _/ _ )___  / /_
#  / / / _ \/ -_) /__/ _ \/ _  / / _ \/ _ `/ _  / _ \/ __/
# /_/ /_//_/\__/\___/\___/\_,_/_/_//_/\_, /____/\___/\__/
#                                    /___/
#
# Support Netro Corporation and keep the hosting machines alive. Your contributions are greatly appreciated! ^^
# We believe in transparency. A report of how much and what exactly was purchased with your contributions will be written up monthly. (This will be in a separate repository)

custom: ["https://www.paypal.me/officialtcgmatt"]
